### ISSUE TITLE
Derived functor context has type variable mismatch

### ISSUE THREAD

**Issue by RyanGlScott** [ndmitchell/derive#9]
I'm trying to use `Data.Derive.Functor` to derive an instance for a data type with a type variable of kind `* -> *`:

```haskell
{-# LANGUAGE TemplateHaskell #-}
{-# OPTIONS_GHC -ddump-splices #-}
module Test where

import Data.Derive.Functor
import Data.DeriveTH

newtype WrappedFunctor f a = WrapFunctor (f a)

$(derive makeFunctor ''WrappedFunctor)
```

This fails to compile, but running it yields a little insight:

```
Lol.hs:10:3-37: Splicing declarations
    derive makeFunctor ''WrappedFunctor
  ======>
    instance Functor f_1627394097 => Functor (WrappedFunctor t1) where
      fmap _f (WrapFunctor a1) = WrapFunctor (fmap _f a1)

Lol.hs:10:3:
    Variable ‘f_1627394097’ occurs more often than in the instance head
      in the constraint: Functor f_1627394097
    (Use UndecidableInstances to permit this)
    In the instance declaration for ‘Functor (WrappedFunctor t1)’
Failed, modules loaded: none.
```

The generated code is pretty close, except that the instance head uses `t1` instead of `f_1627394097`.

**Comment by ndmitchell** [comment]
Any reason for not doing:

    {-# LANGUAGE DeriveFunctor #-}
    module Test where
    newtype WrappedFunctor f a = WrapFunctor (f a)
        deriving Functor

The deriving functor was added to Derive as a prototype for the GHC version. It's pretty complex, and testing suggests the GHC one got some improvements after that.

**Comment by RyanGlScott** [comment]
I'm not planning on using this in production code. I was just curious to see if `derive` was capable of handling this case, since I'm working on a similar TH-based project for deriving `Bifunctor` instances, so I wanted to take some inspiration from `derive`.

Am I correct in assuming that if `derive` sees a type variable of kind `* -> *` that it assumes that it is an instance of `Functor`? Or does it do something more complex?

**Comment by ndmitchell** [comment]
I've no real idea. The code is at https://github.com/ndmitchell/derive/blob/master/Data/Derive/Functor.hs and https://github.com/ndmitchell/derive/blob/master/Data/Derive/Internal/Traversal.hs. I didn't write it, but you're free to reuse what you can. I suspect it's not looking at the kind info at all, since I don't think the version of TH that it was written provided that.

Should you wish to submit patches for your Bifunctor derivation to Derive and ship your derivation that way, I'd be happy to accept them.

Given that there's probably no great reason to use the Functor instance, and fixing it is probably not trivial, I'll close this ticket and just accept it as an expected limitation.
